name: CI (Tests and Lint)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: make test
        run: make test

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.2.1
