name: CI (Tests and Lint)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: go test
        run: go test -mod=vendor --timeout=20m ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.5.1
